name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build and run tests
        run: mvn clean test

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure results
        uses: actions/upload-artifact@v5
        if: always()
        with:
                    name: allure-report
                    path: target/site/allure-maven-plugin
